version: '3'
services:
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - . :/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

      - ./certificates:/etc/nginx/ssl/
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 20052808/safebook
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    expose:
      - "3306"
    ports:
      - "3306:3306"
#    volumes:
#      - ./dbdata:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
#volumes:
#  dbdata:
#    driver: "local"
